import streamlit as st 
import pandas as pd
import joblib
import matplotlib.pyplot as plt
import numpy as np
import mne

st.set_page_config(page_title="Neura - Epilepsy Detection", page_icon=":brain:", layout="wide")
st.markdown("""
<style>
.stAppViewContainer {background-color: #0e1117; }
h1, h2, h3 { color: #b388ff !important; }
.clinical-card {
background-color: #1a1528;
border-left: 5px solid #7c4dff;
padding: 18px;
margin-top: 15px;
}
</style>
""", unsafe_allow_html=True)

import os
import urllib.request

@st.cache_resource
def load_model():
    output = 'Neura_model.pkl'
    dropbox_url = "https://www.dropbox.com/scl/fi/klje5ys9ebjhy1333xdjo/Neura_model.pkl?rlkey=74bxhygpq3h1dj5n2cxiabr9w&st=ob0xrsn3&dl=0"
    url = dropbox_url.replace('dl=0', 'dl=1').replace('www.dropbox.com', 'dl.dropboxusercontent.com')
    if not os.path.exists(output):
        urllib.request.urlretrieve(url, output)
    return joblib.load(output)    

model = load_model()
st.title("Neura - Clinical EEG Analysis & Epilepsy Detection")
st.caption("AI-Powered Research & Screening Assistant for Neurological Signals")

st.warning(
    "Medical Disclaimer: Neura is an AI-assisted researchand screening tool. "
    "Outputs generated by this platform are probabilistic estimates intended soly to support clinical "
    "evaluation and must NOT be used as a standalone medical diagnosis. Always consult a qualified neurologist"
)

st.divider()

col_input, col_display = st.columns([1, 2])

with col_input:
    st.subheader("Data Upload")
    Uploaded_file = st.file_uploader(
        "Upload EEG Recording",
        type=["csv", "edf"],
        help="Select a CSV or EDF file containing raw EEG Signal values."
    )

    if Uploaded_file is not None:
        file_ext = Uploaded_file.name.split(".")[-1].lower()

        if file_ext == "csv":
            df = pd.read_csv(Uploaded_file)
            eeg_data = df.select_dtypes(include=[np.number]).values
            signal = eeg_data[:, 0] if eeg_data.shape[1] > 0 else np.array([])
        elif file_ext == "edf":
            with open("temp_eeg.edf", "wb") as f:
                f.write(Uploaded_file.getbuffer())
            raw = mne.io.read_raw_edf("temp_eeg.edf", preload=False, verbose=False)
        
            eeg_data = raw.get_data(start=0, stop=int(raw.sfreq * 30))
            signal = eeg_data[0]

with col_display:
    st.subheader("Signal Preview")

    if Uploaded_file is not None and len(signal) > 0:
        fig, ax = plt.subplots(figsize=(10, 3.5))
        ax.plot(signal[:1000], color="#b388ff", linewidth=1.2)
        ax.set_title("Primary EEG Channel (First 1,000 Data Points)")
        ax.set_xlabel("Time Samples")
        ax.set_ylabel("Amplitude (uV)")
        ax.grid(True, linestyle="--", alpha=0.5) 
        st.pyplot(fig)

        st.divider()
        st.subheader(" AI Clinical Assessment") 

        features = eeg_data[:1, :178] if eeg_data.ndim == 2 else eeg_data.reshape(1, -1)[:, :178]

        try:
            prediction = model.predict(features)[0]
            probability = model.predict_proba(features)[0]

            m_col1, m_col2, m_col3 = st.columns(3)

            with m_col1:
                if prediction == 1:
                    st.error("Classification: Seizure Activity Detected") 
                else:
                    st.success("Classification: Normal / Non-Seizure")

            with m_col2:
                confidence = max(probability) *100
                st.metric("Model Confidence", f"{confidence:.1f}%")

            with m_col3:
                seizure_prob = probability[1] if len(probability) > 1 else (1.0 if prediction == 1 else 0.0)
                severity_score = seizure_prob * 100
                st.metric("Seizure Severity Risk", f"{severity_score:.1f}%")

            # AI Clinical Reasoning Selection 
            st.markdown("<br>", unsafe_allow_html=True)
            st.subheader("Diagnostic Reasoning & Feature Highlights")

            amp_range = np.ptp(features) 
            std_dev = np.std(features)
            mean_energy = np.mean(features**2)

            exp_col1, exp_col2 = st.columns(2)

            with exp_col1:
                st.markdown(f"""
                <div class='clinical-card'>
                <h4 style='color:#b388ff; margin-top;'>Signal Characteristics</h4>
                <p><b>- Peak Amplitude Range:</b> <code>{amp_range:.2f} &micro;V</code></p>
                <p><b>- Signal Variance:</b> <code>{std_dev:.2f}</coode></p>
                <p><b>- Signal Energy:</b> <code>{mean_energy:.2f}</code></p>
                </div>
                """, unsafe_allow_html=True)


            with exp_col2:
                reasoning = (
                    "High signal variance and elevated amplitude spikes detected, characteristics of hypersynchronous neuronal discharging."
                    if prediction == 1 else 
                    "Voltage fluctuation and signal energy remain within baseline physiological boundaries."
                )
                st.markdown(f"""
                <div class='clinical-card'>
                <h4 style='color:#b388ff; margin-top:0;'>Clinical Reasoning</h4>
                <p>{reasoning}</p>
                </div>
                """, unsafe_allow_html=True)


       
        except Exception as e:    
            st.warning(f"Could not process model prediction: {e}")

    else:
        st.info("Upload an EEG recording (CSV or EDF) on the left to view signal visualization.")                                          
